# Generated by Django 5.2.3 on 2025-07-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
    ]
