# Generated by Django 5.2.3 on 2025-07-01 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_auto_20250701_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESRSDatapointCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('standard', models.CharField(choices=[('ESRS E1', 'ESRS E1 - Climate Change'), ('ESRS E2', 'ESRS E2 - Pollution'), ('ESRS E3', 'ESRS E3 - Water and Marine Resources'), ('ESRS E4', 'ESRS E4 - Biodiversity and Ecosystems'), ('ESRS E5', 'ESRS E5 - Circular Economy'), ('ESRS S1', 'ESRS S1 - Own Workforce'), ('ESRS S2', 'ESRS S2 - Value Chain Workers'), ('ESRS S3', 'ESRS S3 - Affected Communities'), ('ESRS S4', 'ESRS S4 - Consumers and End-Users'), ('ESRS G1', 'ESRS G1 - Business Conduct')], max_length=20)),
                ('section', models.CharField(max_length=100)),
                ('disclosure_requirement', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Environment', 'Environmental'), ('Social', 'Social'), ('Governance', 'Governance')], max_length=20)),
                ('data_type', models.CharField(choices=[('quantitative', 'Quantitative'), ('narrative', 'Narrative'), ('binary', 'Yes/No'), ('date', 'Date'), ('percentage', 'Percentage')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('mandatory', models.BooleanField(default=False)),
                ('ai_guidance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESRS Datapoint',
                'verbose_name_plural': 'ESRS Datapoints',
                'ordering': ['standard', 'disclosure_requirement', 'code'],
            },
        ),
    ]
