# Generated by Django 4.2.7 on 2025-06-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('first_100_tons', 'First 100 Tons CO2e'), ('first_500_tons', 'First 500 Tons CO2e'), ('first_1000_tons', 'First 1000 Tons CO2e'), ('first_5000_tons', 'First 5000 Tons CO2e'), ('first_10000_tons', 'First 10000 Tons CO2e'), ('carbon_neutral', 'Carbon Neutral Achievement'), ('offset_purchase', 'First Offset Purchase'), ('ewaste_donation', 'First E-waste Donation')], max_length=50)),
                ('achieved_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('notification_sent', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_milestones', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'milestone_type')},
            },
        ),
    ]
