# Generated by Django 4.2.7 on 2025-06-30 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonOffset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('price_per_tonne', models.DecimalField(decimal_places=2, max_digits=8)),
                ('co2_offset_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('available_quantity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('forestry', 'Forestry & Land Use'), ('renewable', 'Renewable Energy'), ('methane', 'Methane Reduction'), ('technology', 'Technology Solutions')], max_length=50)),
                ('verification_standard', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['price_per_tonne'],
            },
        ),
        migrations.CreateModel(
            name='OffsetPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('total_co2_offset', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_purchases', to='companies.company')),
                ('offset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carbon.carbonoffset')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_period', models.CharField(max_length=20)),
                ('scope1_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scope2_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scope3_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_emissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprints', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reporting_period')},
            },
        ),
    ]
