# Generated by Django 4.2.7 on 2025-10-04 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbon', '0002_conversationsession_conversationmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='emissions_documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('utility_bill', 'Utility Bill'), ('fuel_receipt', 'Fuel Receipt'), ('travel_receipt', 'Travel Receipt'), ('invoice', 'Invoice'), ('meter_photo', 'Meter Photo'), ('other', 'Other')], default='other', max_length=50)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('gemini_model_used', models.CharField(default='gemini-2.5-flash-lite', max_length=100)),
                ('extraction_error', models.TextField(blank=True, null=True)),
                ('user_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('user_corrections', models.JSONField(blank=True, null=True)),
                ('applied_to_footprint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='companies.company')),
                ('conversation_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_documents', to='carbon.conversationmessage')),
                ('conversation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='carbon.conversationsession')),
                ('footprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='carbon.carbonfootprint')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExtractionField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('field_type', models.CharField(choices=[('date', 'Date'), ('number', 'Number'), ('text', 'Text'), ('currency', 'Currency'), ('quantity', 'Quantity')], max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('user_corrected', models.BooleanField(default=False)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='carbon.uploadeddocument')),
            ],
            options={
                'ordering': ['document', 'field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['company', 'document_type'], name='carbon_uplo_company_e01098_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['extraction_status'], name='carbon_uplo_extract_b1197c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['expires_at'], name='carbon_uplo_expires_3999d1_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['created_at'], name='carbon_uplo_created_224e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextractionfield',
            index=models.Index(fields=['document', 'field_name'], name='carbon_docu_documen_1716af_idx'),
        ),
        migrations.AddIndex(
            model_name='documentextractionfield',
            index=models.Index(fields=['confidence'], name='carbon_docu_confide_73f7a4_idx'),
        ),
    ]
