# Generated by Django 4.2.7 on 2025-06-30 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EwasteEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop Computer'), ('monitor', 'Monitor'), ('tablet', 'Tablet'), ('smartphone', 'Smartphone'), ('printer', 'Printer'), ('server', 'Server'), ('other', 'Other')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('donation_date', models.DateField()),
                ('estimated_co2_saved', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbon_credits_generated', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewaste_entries', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'E-waste entries',
                'ordering': ['-donation_date'],
            },
        ),
    ]
